# Generated by Django 4.2.3 on 2023-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acc_name", models.CharField(max_length=30, verbose_name="악세서리 이름")),
                (
                    "image_path",
                    models.ImageField(
                        null=True, upload_to="media/acc", verbose_name="악세서리 사진"
                    ),
                ),
                (
                    "acc_add_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="악세서리 추가시간"),
                ),
            ],
            options={
                "verbose_name": "악세서리",
                "verbose_name_plural": "악세서리",
                "db_table": "accessory",
            },
        ),
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clothes_type", models.CharField(max_length=16, verbose_name="옷 종류")),
                ("clothes_name", models.CharField(max_length=30, verbose_name="옷 이름")),
                (
                    "image_path",
                    models.ImageField(
                        null=True, upload_to="media/clothes", verbose_name="옷 사진"
                    ),
                ),
                (
                    "clothes_add_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="옷 추가시간"),
                ),
            ],
            options={
                "verbose_name": "옷",
                "verbose_name_plural": "옷",
                "db_table": "clothes",
            },
        ),
        migrations.CreateModel(
            name="Shoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shoes_name", models.CharField(max_length=30, verbose_name="신발 이름")),
                (
                    "image_path",
                    models.ImageField(
                        null=True, upload_to="media/shoes", verbose_name="신발 사진"
                    ),
                ),
                (
                    "shoes_add_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="신발 추가시간"),
                ),
            ],
            options={
                "verbose_name": "신발",
                "verbose_name_plural": "신발",
                "db_table": "shoes",
            },
        ),
    ]
