# Generated by Django 4.2.3 on 2023-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="memo",
            field=models.TextField(verbose_name="메모"),
        ),
    ]
